import Head from 'next/head';
import Layout from '../../components/Layout';
import FinancialAndManagerialAccounting from '../../components/Services/FinancialAndManagerialAccounting';

const financial_and_managerial_accounting_service = () => {
    return (
        <>
            <Head>
                <title>Financial and Managerial Accounting Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Layout>
                <div>
                    <FinancialAndManagerialAccounting />
                </div>
            </Layout>
            
        </>
    );
};

export default financial_and_managerial_accounting_service;