import Head from 'next/head';
import Layout from '../../components/Layout';
import FinancialManagementServices from '../../components/Services/FinancialManagementServices';

const financial_management_services = () => {
    return (
        <>
            <Head>
                <title>Financial Management Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Layout>
                <div>
                    <FinancialManagementServices />
                </div>
            </Layout>
            
        </>
    );
};

export default financial_management_services;