import Head from 'next/head';
import Layout from '../../components/Layout';
import ImplementationOfNewAccountingSystem from '../../components/Services/ImplementationOfNewAccountingSystem';

const implementation_of_new_accounting_system = () => {
    return (
        <>
            <Head>
                <title>Implementation of new accounting system</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Layout>
                <div>
                    <ImplementationOfNewAccountingSystem />
                </div>
            </Layout>
            
        </>
    );
};

export default implementation_of_new_accounting_system;